services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin123"
      MYSQL_DATABASE: "daily_diet"
      MYSQL_ROOT_PASSWORD: "admin123"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      # For windows
      - /c/labs/formacao_python_rocketseat_modulo_4_desafio_2_daily_diet_api/mysql:/var/lib/mysql/